---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [pre-commit]
repos:
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.32.1
  hooks:
  - id: check-github-actions
    additional_dependencies:
    - pip_system_certs==4.0
  - id: check-dependabot
    additional_dependencies:
    - pip_system_certs==4.0
- repo: https://github.com/google/yamlfmt
  rev: v0.16.0
  hooks:
  - id: yamlfmt
    exclude: (.clang-(format|tidy)|tests/python/test_.*)
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.2
  hooks:
  - id: ruff
  - id: ruff-format
- repo: https://github.com/Mateusz-Grzelinski/actionlint-py
  rev: v1.7.7.23
  hooks:
  - id: actionlint
    additional_dependencies: [pyflakes>=3.0.1, shellcheck-py>=0.9.0.5]
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: 3.2.0
  hooks:
  - id: editorconfig-checker
    alias: ec
# this should go last since it will fix line endings broken by other tools
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: no-commit-to-branch
    args: [--branch, main]
  - id: trailing-whitespace
    stages: [pre-commit]
  - id: check-added-large-files
    stages: [pre-commit]
  - id: check-case-conflict
  - id: mixed-line-ending
    args: [--fix=lf]
    stages: [pre-commit]
  - id: end-of-file-fixer
    stages: [pre-commit]
  - id: check-yaml
  - id: check-xml
  - id: check-json
  - id: check-toml
  - id: pretty-format-json
    args: [--autofix, --no-sort-keys, --indent=4]
    exclude: .*\.ipynb$
  - id: check-symlinks
  - id: debug-statements
  - id: fix-byte-order-marker
