---
name: mirror from gitlab to github

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:
  push:

# dune-fem dune-grid-glue dune-grid dune-common dune-istl dune-localfunctions dune-geometry dune-functions dune-pdelab dune-typetree dune-uggrid dune-spgrid dune-testtools dune-alugrid dune-python

jobs:
  repos:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.repos.outputs.repos }}
    steps:
    - uses: actions/checkout@v5
    - id: repos
      run: |
        { echo 'repos<<EOF' ;
          python ./repos_to_matrix.py ;
          echo 'EOF' ; } >> "${GITHUB_OUTPUT}"

  mirror:
    runs-on: ubuntu-latest
    needs: repos
    strategy:
      fail-fast: false
      # each job gets "slug" and "url" and "module_name"
      matrix: ${{ fromJson(needs.repos.outputs.repos) }}
    steps:
    - uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets[format('SSH_KEY_{0}', matrix.keyname )] }}
    - run: |
        git clone --mirror ${{ matrix.url }} ${{ matrix.module_name }}
        cd ${{ matrix.module_name }}
        git remote set-url --push origin git@github.com:dune-mirrors/${{ matrix.module_name }}.git
        git fetch -p origin
        # Exclude refs created by GitHub for pull request.
        git for-each-ref --format 'delete %(refname)' refs/merge-requests | git update-ref --stdin
        git push --mirror

      shell: bash -l {0}
